
services:
  - type: web
    name: sudoku-harsha
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -t 120 main:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
